# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ranadebsaha2002@gmail.com
author_name: ranadebsaha
contract_name: hello
deployment_language: python
preset_name: starter
project_name: algo-contracts

